#!/usr/bin/env python

import argparse
import requests
from datetime import date

LICENSE_ROOT_URL = 'https://raw.githubusercontent.com/adamheins/licenses/master'

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('type', help='Type of license to use.')
    parser.add_argument('-n', '--name', help='Specify the name in the license.',
                        required=True)
    args = parser.parse_args()

    url = '/'.join([LICENSE_ROOT_URL, args.type])
    req = requests.get(url)
    text = req.text
    text = text.replace('<year>', str(date.today().year))
    text = text.replace('<name>', args.name)

    with open('LICENSE', 'w') as license:
        license.write(text)

if __name__ == '__main__':
    main()
